wcias_joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 50


wcias_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'left_main_wheel_joint'
  right_wheel: 'right_main_wheel_joint'
  publish_rate: 50
  pose_covariance_diagonal : [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  cmd_vel_timeout: 0.25

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Base frame_id
  base_frame_id: base_footprint
  odom_frame_id: odom
  enable_odom_tf: true

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 2.0   # m/s
      has_acceleration_limits: true
      max_acceleration       : 3.0   # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 6.0   # rad/s
      has_acceleration_limits: true
      max_acceleration       : 6.0 # rad/s^2

