topics:
- name    : move_base
  topic   : move_base/cmd_vel
  timeout : 0.5
  priority: 1
- name    : external
  topic   : /djoy/cmd_vel
  timeout : 0.5
  priority: 2

locks:
- name    : e_stop
  topic   : /djoy/e_stop
  timeout : 0.0
  priority: 255
